name: bfsi
description: BFSI app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency injection
  get_it: ^7.6.4

  # Navigation
  routemaster: ^1.0.1

  # Error reporting
  sentry_flutter: ^7.14.0

  #Networking
  dio: ^5.3.3
  http_parser: ^4.0.2
  pretty_dio_logger: ^1.3.1
  gql_dio_link: ^1.0.1+1

  #util
  fimber: ^0.7.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_lints: ^3.0.1

  # Auto router generator
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  # testing dependencies
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
          weight: 400
        - asset: fonts/Mulish-Medium.ttf
          weight: 500
        - asset: fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
        - asset: fonts/Mulish-ExtraBold.ttf
          weight: 800

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800


